#!/bin/bash

# list2(){
# netstat  -t 2>/dev/null | grep :28772 | awk '{print $5}' | cut -d: -f1 | uniq -c
# }


# list(){
# echo "debut"
# pid=`pgrep smalldb`
# echo "$pid"
# netstat -bn "$pid"
# echo "fin"
# }

sync(){
pid=`pgrep smalldb`
kill -SIGUSR1 "$pid"
}

stop(){
pid=`pgrep smalldb`
kill -SIGINT "$pid"
}