#!/bin/bash
#remember to use chmod u+x smalldbctl
#and chmod 744 smalldbctl
#in terminal
#syntax is : monitoring

list(){
pid=`pgrep smalldb`
lsof -i -P -n | grep "$pid" | awk '{print $9}' | cut -d: -f1
}

sync(){
pid=`pgrep smalldb`
kill -SIGUSR1 "$pid"
}

stop(){
pid=`pgrep smalldb`
kill -SIGINT "$pid"
}