name: Build and test C++ code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3
      - name: Build C++ code
        run: |
          cd src
          make
      - name: Run tests (1/3)
        run: |
          cd tests
          bash ./run_tests.sh
        env:
          CI: true
      - name: Run tests (2/3)
        run: |
          cd tests
          bash ./run_tests.sh
        env:
          CI: true
      - name: Run tests (3/3)
        run: |
          cd tests
          bash ./run_tests.sh
        env:
          CI: true
