name: Build and test C++ code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build C++ code
        run: |
          cd src
          make
      - name: Run tests
        run: |
          cd tests
          bash ./run_tests.sh
      - name: Start the database
        run: cd src && ./smalldb students-data.bin
      - name: Create a client and send data to the database
        run: |
          cd src && ./sdbsh
          insert Romain Markowitch 1 Info 05/05/2003
          insert Pol Marnette 2 Info 12/07/2001
          select fname=Pol
        env:
          CI: true
